### PR TITLE
Add MEMOIZE function to automatically memoize a function

### PR DESCRIPTION
**Pull request by enbyautumn**

### CODE REVIEW

**Comment by enbyautumn** [comment]
I would be happy to write out a page for the gitbook as well, but i was not able to find how to edit that

**Comment by TodePond** [comment]
Hey awesome thanks! Do you think we could rename the global function from `MEMOIZE` to `memo`? Then I'll merge it!

I'll change the gitbook settings at some point so that it can be edited via GitHub :)

**Comment by TodePond** [comment]
You should be able to submit changes to the `docs` branch now to change the gitbook docs

**Comment by enbyautumn** [comment]
Is there a specific way to stylize optional arguments in the documentation? i was thinking of doing `memo(function, [keyMaker])` but would like to avoid confusion

**Comment by TodePond** [comment]
Great! Thanks! 

And yes, that style is good!

**Pull request merged**
